### ISSUE TITLE
trparse fails to distiguish bison production rules with different casings

### ISSUE THREAD

**Issue by SKalt** [kaby76/Domemtech.Trash#10]
In a bison grammar there were two production rules distinguished by case: [`character`][1] and [`Character`][2] (1).  `trparse gram.y | trconvert | trsponge` normalized the distinct symbols in the input grammar to `character` in the output grammar. That's a reasonable way to deal with a pathological grammar, but I think it's a bug in how `trparse` parses yacc-compatible grammars: the [yacc spec][3] says that 

> [Rule] Names are of arbitrary length, made up of letters, periods ( '.' ), underscores ( '_' ), and non-initial digits. Uppercase and lowercase letters are distinct.

I'd be happy to take a shot at addressing this bug if you point me to the right area of the code.

<hr>

1: there was also a `CHARACTER` a token to spice things up, but `trparse` handled that perfectly.

[1]: https://github.com/postgres/postgres/blob/b0483263dda0824cc49e3f8a022dab07e1cdf9a7/src/backend/parser/gram.y#L13081
[2]: https://github.com/postgres/postgres/blob/b0483263dda0824cc49e3f8a022dab07e1cdf9a7/src/backend/parser/gram.y#L13036
[3]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/yacc.html#tag_20_159_13_02

**Comment by kaby76** [comment]
You are right. the two rules for "Character" and "character" in gram.y are mapped to "character", but by trconvert. I had assumed everything in the Bison file was a parser rule, but it's not.

The renaming in the converter [here](https://github.com/kaby76/Domemtech.TrashBase/blob/main/LanguageServer/ConvertBison.cs#L80) and [here](https://github.com/kaby76/Domemtech.TrashBase/blob/main/LanguageServer/ConvertBison.cs#L143) and likely other places must be fixed. I'm not sure where I put in the renaming for RHS symbols, but that must be examined as well.

I will make a fix today to the existing code.

But, I am redoing the backend of Trash ("TrashBase") very soon, so this code will be moved into self-contained plugin modules, where each module will describe the language (Antlr, Bison/Yacc, EBNF, ABNF, etc.), syntax, static semantics, and conversion in a target-language independent way.

**Comment by kaby76** [comment]
For this bug, I changed the code to append an underscore to the name for similarly named LHS symbols. So, `Character` in the original Bison grammar is changed to `character` and `character` changed to `character_`. These are legal parser rule names. I don't know whether the same rule name can exist as a LHS symbol for more than one Bison rule, but I will check, and introduce code to merge the rules since Antlr does not allow multiple rules with the same LHS symbol. If the rename is not desired, then trrename can be used to then fix the generated Antlr grammar.

**Comment by SKalt** [comment]
I cloned, reinstalled, reran my build script and can verify the fix works!
