### ISSUE TITLE
Trash Build

### ISSUE THREAD

**Issue by ydenizyamac** [kaby76/Domemtech.Trash#7]
Hello,

I'm trying to build this project but it could not find TrashBase nuget package. can you please help me about this?

I'll use it to convert antlr2 grammar to antlr4 if I can by the way.

Edit: I have tried to use VS2019 extension, but it throws an error for Antlr4.Runtime.Standard.dll and I could not work it out.

Thanks,

Best Regards

**Comment by kaby76** [comment]
Sorry, I haven't pushed the TrashBase package to Nuget yet. I'll do that now so you can try to do a build. I think it should be able to do the convert, but I haven't tested it recently. You'd have to do something like `trparse -f ANTLRv2.g2 -t antlr2 | trconvert | trprint`. I'd recommend that you just install the don't tools though:

	#version="--version 0.7.0"
	version=""

	dotnet tool install -g tranalyze $version
	dotnet tool install -g trconvert $version
	dotnet tool install -g trfold $version
	dotnet tool install -g trfoldlit  $version
	dotnet tool install -g trgen  $version
	dotnet tool install -g trgroup  $version
	dotnet tool install -g trjson  $version
	dotnet tool install -g trkleene  $version
	dotnet tool install -g trparse  $version
	dotnet tool install -g trprint  $version
	dotnet tool install -g trrename  $version
	dotnet tool install -g trst  $version
	dotnet tool install -g trstrip  $version
	dotnet tool install -g trtext  $version
	dotnet tool install -g trtokens  $version
	dotnet tool install -g trtree  $version
	dotnet tool install -g trunfold  $version
	dotnet tool install -g trungroup  $version
	dotnet tool install -g trwdog  $version
	dotnet tool install -g trxgrep  $version
	dotnet tool install -g trxml  $version
	dotnet tool install -g trxml2  $version

And, since you are only interested in the conversion, just install trparse, trconvert, trprint.

Note, if you are doing it from Powershell or Cmd, then just remove the "$version".

**Comment by ydenizyamac** [comment]
Hello,

Thanks for the answer. I'm getting errors when trying to convert;


line 1:0 mismatched input 'options\r\n{' expecting {'lexer', 'parser', 'grammar'}
line 3:10 mismatched input '=' expecting SEMI
line 4:11 mismatched input '=' expecting {BEGIN_ARGUMENT, OPTIONS, 'returns', 'locals', 'throws', COLON, AT}
line 7:24 missing COLON at ';'
line 9:0 mismatched input 'options {' expecting {<EOF>, 'mode'}

Error in parse of C:\Users\deniz.yamac\Desktop\Domemtech.Trash-main\Release\net5\Example.g4

I'm not much experienced with the antlr grammar but it throws an error in g4 file? 

Command: trparse -f .\VeriParkExpressions.g -t antlr2 | trconvert

**Comment by kaby76** [comment]
It's not parsing your grammar. Unfortunately, I didn't have a lot of Antlr2 grammar samples to go by (the ones I did find I placed them [here](https://github.com/antlr/grammars-v4/tree/master/antlr/antlr2/examples)). If you can pass me the grammar file, I can see what needs to be done to get it to parse, and convert. -Ken

**Comment by kaby76** [comment]
I reproduced the problem. Yes, trparse is trying to read too much. It has to because people split grammars in Antlr4 (e.g., [the Java9 grammar](https://github.com/antlr/grammars-v4/tree/master/java/java9)). But, that doesn't happen in Antlr2. So, it's trying to read other grammars that are Antlr4 as an older type. The workaround is to just copy the Antlr2 grammar to a clean directory, cd to it, and run the tool.

I'll have a fix later today.

**Comment by ydenizyamac** [comment]
I'm trying to convert it manually, but if you can make any suggestion it would be great, 

thank you 

best regards

[AppExpressions.zip](https://github.com/kaby76/Domemtech.Trash/files/6521688/AppExpressions.zip)

**Comment by kaby76** [comment]
It also looks like the Antlr2 grammar I use to parse Antlr2 grammars needs work. After removing some code blocks and "< AST = ...>" code, I was finally able to get it to convert. See attached file. 
[xx.zip](https://github.com/kaby76/Domemtech.Trash/files/6521820/xx.zip)

**Comment by kaby76** [comment]
Sorry, there were a number of other problems. Here is a grammar that actually gets through the Antlr4 tool. I don't have any input, so I couldn't test per se. 
[xx.zip](https://github.com/kaby76/Domemtech.Trash/files/6521994/xx.zip)


There are a number of wonderful things I don't do right with this grammar. Would you mind if I add it to the grammars-v4/antlr/antlr2/examples area, and include it in a test suite for the Trash toolchain? --Ken

**Comment by ydenizyamac** [comment]
Hello there,
Firstly, you can use it as an example, of course :)
And yes ,  it works now. I'm trying to implement nodes in c# for literals, like StringLiteralNode, I hope I'm doing it correctly :)

**Comment by ydenizyamac** [comment]
I could not update custom operators and nodes antlr4 correctly. I did some part but I'm confused. Can you please guide or make any suggestion for me to update BaseAST part correctly. We have nodes, operators with same base abstract class. In older implementation, opreators running in parser for example. I could not do it that way.

Old AST's are using getFirstChild(), getNextSibling() etc. I simulated that with children but it does not look right.

Thanks, 
Best Regards

**Comment by kaby76** [comment]
I recommend that you just use the CST, which is produced automatically in version 4, and add the `contextSuperClass` to set the node type base class you want to create in the tree. It won't be exactly a one-to-one mapping with your old AST, so you will need to rewrite some of your code. All that was on the AST is still in the CST, and a little more. E.g., you can then access a particular child with an index using getChild(index), or use the name of the symbol used in the RHS to get one or more children of that type, e.g., "foo -> bar bar other;" => "foo_cst_node.bar()".

**Comment by ydenizyamac** [comment]
I managed to work it out, thank you for your support.
